[tox]
env_list = fmt,lint,unit,integration
min_version = 4.0
skipsdist = true

[vars]
charm_dir = {tox_root}/gitlab-runner
src_path = {[vars]charm_dir}/src
tests_path = {[vars]charm_dir}/tests

[testenv]
description = Shared testenv settings
changedir = {[vars]charm_dir}
basepython = {env:TOXPYTHON:python3}
passenv = *
deps =
    -r {[vars]charm_dir}/requirements.txt
    -r {[vars]charm_dir}/requirements-dev.txt
setenv =
    PYTHONPATH = {[vars]src_path}

[testenv:fmt]
description = Verify code formatting
skip_install = true
deps =
    black
commands =
    black --check --diff src tests

[testenv:lint]
description = Run static analysis checks
skip_install = true
deps =
    -r {[vars]charm_dir}/requirements-dev.txt
commands =
    flake8 --config .flake8 src tests

[testenv:unit]
description = Run unit tests
commands =
    pytest -v {[vars]tests_path} {posargs}

[testenv:integration]
description = Run integration tests
commands =
    pytest -v -s --tb native --log-cli-level=INFO {[vars]tests_path}/integration {posargs}

[flake8]
# E501 line too long (88 > 79 characters)
# E741 ambiguous variable name 'l' (don't modify benhcmarks just for that)
# W503 line break before binary operator
ignore = E501,E741,W503
exclude = ./gitlab-runner/build/*
