# Template for global config.toml

concurrent = {{concurrent}}
check_interval = {{checkinterval}}
{% if sentrydsn %}
sentry_dsn = "{{sentrydsn}}"
{% endif %}
log_level = "{{loglevel}}"
log_format = "{{logformat}}"

[session_server]
  session_timeout = 1800